name: "Punishment-Manager"
version: "1.0"
author: "xxAROX"
website: "https://github.com/HQGames/Punishment-Manager"
description: "Punishment-Manager for HQGames by xxAROX."

api:
  - "4.0.0"
main: HQGames\PunishmentManager\PunishmentManager
